### ISSUE TITLE
Add support for accessing bridge metadata

### ISSUE THREAD

**Issue by slrtbtfs** [yuqio/huelib-rs#12]
Hue bridges have an endpoint at `<bridge_ip>/description.xml` that allows retrieving meta data about the bridge.

It would be nice if that meta data was accessible through this library. Especially the UDN/UUID field might be useful to check whether a bridge has changed its IP address.

**Comment by yuqio** [comment]
This is now available in [version 0.12.0](https://github.com/yuqio/huelib-rs/releases/tag/v0.12.0). You have to enable the `upnp-description` cargo feature and you can then get the metadata by calling the `bridge::description` function.

**Comment by slrtbtfs** [comment]
Great, thanks!
