### ISSUE TITLE
Resourcelink Creator "classid" 

### ISSUE THREAD

**Issue by jrray** [yuqio/huelib-rs#8]
Hello,

I encountered an error when attempting to create a new resource link, it was rejecting the attribute "class_id" as unknown, and started working once I renamed this field to "classid" instead.

https://github.com/yuqio/huelib-rs/blob/c07d3d85070fe6cf95c9a575833c50c84a4d1f09/src/resource/resourcelink.rs#L130

**Comment by yuqio** [comment]
Thanks for reporting. This is now fixed in [version 0.6.1](https://github.com/yuqio/huelib-rs/releases/tag/v0.6.1)
